### PR TITLE
Add build step to npm prepare

### PR DESCRIPTION
**Pull request by michielbdejong**
It's hard to test it without actually tagging @2.0.6 and trying it out, but I think this should probably be enough to fix issue #31.

### CODE REVIEW

**Comment by michielbdejong** [comment]
See also https://stackoverflow.com/questions/29738381/how-to-publish-a-module-written-in-es6-to-npm for more info.

**Comment by michielbdejong** [comment]
> Why /src/ ... does that start at the user's file root??

Luckily not, that would be scary! :) The syntax for `.npmignore` is the same as for `.gitignore`, see https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#Ignoring-Files.
Specifically "You can start patterns with a forward slash (/) to avoid recursivity." and these two entries in the example on that page:
```.gitignore
# only ignore the TODO file in the current directory, not subdir/TODO
/TODO

# ignore all files in any directory named build
build/
```

**Comment by michielbdejong** [comment]
@timbl Replying to your question on gitter,
> What does npmignore of /src/ do ? remove all of the src tree from npm?

yes, or more precisely, avoids publishing it. So the idea behind the StackOverflow answer I linked to is that you publish only `./dist` and not `./src` to npm. On git you do the opposite (track only `./src` and not `./dist`).

**Comment by michielbdejong** [comment]
We now have https://github.com/solid/meeting-pane/commit/7346f135579212fcd0451e748ba5c2188acdcfc0 which solves part of the problem.

**Comment by megoth** [comment]
For consistency, remember to add these kinds of changes to all related mashlib/solid-panes projects.

**Comment by michielbdejong** [comment]
Good point! I added an issue to chat-pane. It looks like folder-pane is still in JS, any others you are aware of?

**Comment by megoth** [comment]
> Good point! I added an issue to chat-pane. It looks like folder-pane is still in JS, any others you are aware of?

I guess solid-panes and solid-ui might be the only ones, for now. But have to remember to add them to other projects as we migrate them to TS.

**Pull request closed without merging**
